- hosts: app-server
  become: yes

  tasks:
    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: gtsintsadze/nodejs-rest-api
        tag: latest
        source: pull

    - name: Run container
      community.docker.docker_container:
        name: nodejs-app
        image: gtsintsadze/nodejs-rest-api:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:5656"
